language: java
sudo: false

jdk:
  - oraclejdk8

# ask travis to doanload all revisions, our build version depends on this
git:
  depth: 10000

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

before_install:
  chmod +x gradlew

env:
  global:
    # no coloring during the build
    - TERM=dumb
    #secure:

script:
  # build all with unit tests running
  - ./gradlew clean buildProduct

after_success:
  # publish code coverage information
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # archive output folder before publishing
  - zip -r tiro-$TRAVIS_BUILD_NUMBER.zip build/output/tiro

# http://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: R56pkHPRNPduhLGkABUmhhMgs3/dQbknXku21qIUKche0aZLWIsdX4Qj/qk60bKEFtHblhuCuO+X2gLQ76fHK4S1nuqfFsf1jOinXmgkZhIREq0WCAwilqRqt7m09JmWFMgQwUNYE6Ure0z21qpSOpBrDc6/VkciGIzLNc6f9Tts7GrH2akbuJvZ54NJ0yQfuM/d6m6gpP2WNm8EbllWEPFJ9Clj3pnpedYbeb1eooODQ8U5o24C4AK5kcowY28TX5TebgVLDphKFuGzBerQRWdKYGYi9rgUZ3DbLZawmi3v1J+UEHkSRwY2yeiJ9nzjlz+C+DI7bQ34iUBqmL4VqahNuVoqczTnN/tuk5l1V1+FAkTAxe+HRsmFSwXU87klK6aD4mDvjitH6hCa351xzjMae1ZDmVS2BaQGckYwHXXLuHCXIEEhQD0CDadu8W+YSyf1z+Ix3nPG+0Z1/I6/y1WLoT19kT20pqHfsGxguAPdWkZrOLzqOiBhCy4TCC0zBPxarXtdQhp5XD8uyKOIQHEFmUqeU3/xqAFRFAdK5CUENclYw0JradD3VL3pRlu1d7hAAuJdDFXtl5DBW3cOSs3m7HM0mr//6KR8mYgaDVumJfB9FFjPkdCT5geHNnIn1E+JfTGG3pUW++kaoWAh6DkfCMSKqoo4BtTLN3XlNM4=
  file: tiro-$TRAVIS_BUILD_NUMBER.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

notifications:
  email: false
  webhooks:
    urls:
      - $GITTER_WEB_HOOK
#	    - https://webhooks.gitter.im/e/f9d875b20132dda64fbe
    on_success: always  # options: [always|never|change] default: always
    on_failure: never   # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
